addSbtPlugin("com.github.sbt"                    % "sbt-pgp"          % "2.3.1")
addSbtPlugin("com.github.sbt"                    % "sbt-release"      % "1.4.0")
addSbtPlugin("org.scalameta"                     % "sbt-scalafmt"     % "2.4.6")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings" % "3.0.2")
addSbtPlugin("ch.epfl.scala"                     % "sbt-scalafix"     % "0.14.4")
